// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Supermercado.Backend.Data;

#nullable disable

namespace Supermercado.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251027011244_entidad_Tercero_again")]
    partial class entidad_Tercero_again
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Supermercado.Shared.Entities.Categoria_Producto", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaId"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("categoriaId");

                    b.HasIndex("descripcion")
                        .IsUnique();

                    b.ToTable("Categoria_Productos");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Producto", b =>
                {
                    b.Property<int>("producto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("producto_id"));

                    b.Property<int>("FK_categoria_id")
                        .HasColumnType("int");

                    b.Property<int>("FK_codigo_iva")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("codigo_barras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("codigo_producto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("precio_unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<int>("stock_maximo")
                        .HasColumnType("int");

                    b.Property<int>("stock_minimo")
                        .HasColumnType("int");

                    b.HasKey("producto_id");

                    b.HasIndex("FK_categoria_id");

                    b.HasIndex("FK_codigo_iva");

                    b.HasIndex("codigo_barras")
                        .IsUnique();

                    b.HasIndex("codigo_producto")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Rol", b =>
                {
                    b.Property<int>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rol_id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("rol_id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Tarifa_IVA", b =>
                {
                    b.Property<int>("tarifa_iva_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tarifa_iva_id"));

                    b.Property<string>("codigo_Iva")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("tarifa_iva_id");

                    b.HasIndex("codigo_Iva")
                        .IsUnique();

                    b.HasIndex("tarifa_iva_id")
                        .IsUnique();

                    b.ToTable("Tarifa_IVAs");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Tercero", b =>
                {
                    b.Property<int>("tercero_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tercero_id"));

                    b.Property<int>("FK_codigo_ident")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("es_cliente")
                        .HasColumnType("bit");

                    b.Property<bool>("es_proveedor")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero_identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tercero_id");

                    b.HasIndex("FK_codigo_ident");

                    b.HasIndex("numero_identificacion")
                        .IsUnique();

                    b.HasIndex("tercero_id")
                        .IsUnique();

                    b.ToTable("Terceros");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.TiposIdentificacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipoDocumentoID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("tipoDocumentoID")
                        .IsUnique();

                    b.ToTable("TiposIdentificacions");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuario_id"));

                    b.Property<int>("FK_rol_id")
                        .HasColumnType("int")
                        .HasColumnName("FK_rol_id");

                    b.Property<bool>("activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("fecha_modificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("usuario_id");

                    b.HasIndex("FK_rol_id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("nombre_usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Producto", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.Categoria_Producto", "Categoria")
                        .WithMany()
                        .HasForeignKey("FK_categoria_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supermercado.Shared.Entities.Tarifa_IVA", "TarifaIVA")
                        .WithMany()
                        .HasForeignKey("FK_codigo_iva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("TarifaIVA");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Tercero", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.TiposIdentificacion", "ID")
                        .WithMany()
                        .HasForeignKey("FK_codigo_ident")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ID");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Usuario", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("FK_rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
