// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Supermercado.Backend.Data;

#nullable disable

namespace Supermercado.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Supermercado.Shared.Entities.Categoria_Producto", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoriaId"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("categoriaId");

                    b.HasIndex("descripcion")
                        .IsUnique();

                    b.ToTable("Categoria_Productos");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Consecutivo", b =>
                {
                    b.Property<int>("consecutivo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("consecutivo_Id"));

                    b.Property<int>("FK_codigo_tipodcto")
                        .HasColumnType("int");

                    b.Property<bool>("afecta_inv")
                        .HasColumnType("bit");

                    b.Property<string>("cod_consecut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("consecutivo_actual")
                        .HasColumnType("int");

                    b.Property<int>("consecutivo_fin")
                        .HasColumnType("int");

                    b.Property<int>("consecutivo_ini")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("es_entrada")
                        .HasColumnType("bit");

                    b.HasKey("consecutivo_Id");

                    b.HasIndex("FK_codigo_tipodcto");

                    b.HasIndex("cod_consecut")
                        .IsUnique();

                    b.ToTable("consecutivos");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Detalle_Factura", b =>
                {
                    b.Property<int>("detalle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("detalle_id"));

                    b.Property<int>("FK_factura_id")
                        .HasColumnType("int");

                    b.Property<int>("FK_producto_id")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("descuento_porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("descuento_valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("precio_unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("detalle_id");

                    b.HasIndex("FK_factura_id");

                    b.HasIndex("FK_producto_id");

                    b.HasIndex("detalle_id")
                        .IsUnique();

                    b.ToTable("DetallesFactura");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Factura", b =>
                {
                    b.Property<int>("factura_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("factura_id"));

                    b.Property<int>("FK_movimiento_id")
                        .HasColumnType("int");

                    b.Property<decimal>("total_bruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total_descuentos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total_neto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("factura_id");

                    b.HasIndex("FK_movimiento_id");

                    b.HasIndex("factura_id")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Metodos_Pago", b =>
                {
                    b.Property<int>("id_metodo_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_metodo_pago"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("codigo_metpag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("metodo_pago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_metodo_pago");

                    b.HasIndex("codigo_metpag")
                        .IsUnique();

                    b.HasIndex("id_metodo_pago")
                        .IsUnique();

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Movimiento", b =>
                {
                    b.Property<int>("movimiento_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("movimiento_id"));

                    b.Property<int>("FK_codigo_tipodoc")
                        .HasColumnType("int");

                    b.Property<int>("FK_consecutivo_id")
                        .HasColumnType("int");

                    b.Property<int>("FK_tercero_id")
                        .HasColumnType("int");

                    b.Property<int>("FK_usuario_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("numero_documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("movimiento_id");

                    b.HasIndex("FK_codigo_tipodoc");

                    b.HasIndex("FK_consecutivo_id");

                    b.HasIndex("FK_tercero_id");

                    b.HasIndex("FK_usuario_id");

                    b.HasIndex("movimiento_id")
                        .IsUnique();

                    b.HasIndex("numero_documento")
                        .IsUnique();

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Pago_Factura", b =>
                {
                    b.Property<int>("pago_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pago_id"));

                    b.Property<int>("FK_factura_id")
                        .HasColumnType("int");

                    b.Property<int>("FK_id_metodo_pago")
                        .HasColumnType("int");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("referencia_pago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("pago_id");

                    b.HasIndex("FK_factura_id");

                    b.HasIndex("FK_id_metodo_pago");

                    b.HasIndex("pago_id")
                        .IsUnique();

                    b.ToTable("PagosFactura");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Producto", b =>
                {
                    b.Property<int>("producto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("producto_id"));

                    b.Property<int>("FK_categoria_id")
                        .HasColumnType("int");

                    b.Property<int>("FK_codigo_iva")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("codigo_barras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("codigo_producto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("precio_unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<int>("stock_maximo")
                        .HasColumnType("int");

                    b.Property<int>("stock_minimo")
                        .HasColumnType("int");

                    b.HasKey("producto_id");

                    b.HasIndex("FK_categoria_id");

                    b.HasIndex("FK_codigo_iva");

                    b.HasIndex("codigo_barras")
                        .IsUnique();

                    b.HasIndex("codigo_producto")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Rol", b =>
                {
                    b.Property<int>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rol_id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("rol_id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Tarifa_IVA", b =>
                {
                    b.Property<int>("tarifa_iva_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tarifa_iva_id"));

                    b.Property<string>("codigo_Iva")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("tarifa_iva_id");

                    b.HasIndex("codigo_Iva")
                        .IsUnique();

                    b.HasIndex("tarifa_iva_id")
                        .IsUnique();

                    b.ToTable("Tarifa_IVAs");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Tercero", b =>
                {
                    b.Property<int>("tercero_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tercero_id"));

                    b.Property<int>("FK_codigo_ident")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("es_cliente")
                        .HasColumnType("bit");

                    b.Property<bool>("es_proveedor")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero_identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tercero_id");

                    b.HasIndex("FK_codigo_ident");

                    b.HasIndex("numero_identificacion")
                        .IsUnique();

                    b.HasIndex("tercero_id")
                        .IsUnique();

                    b.ToTable("Terceros");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.TipoDcto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipoDctos");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.TiposIdentificacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipoDocumentoID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("tipoDocumentoID")
                        .IsUnique();

                    b.ToTable("TiposIdentificacions");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuario_id"));

                    b.Property<int>("FK_rol_id")
                        .HasColumnType("int")
                        .HasColumnName("FK_rol_id");

                    b.Property<bool>("activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("fecha_modificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("usuario_id");

                    b.HasIndex("FK_rol_id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("nombre_usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Consecutivo", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.TipoDcto", "ID")
                        .WithMany()
                        .HasForeignKey("FK_codigo_tipodcto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ID");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Detalle_Factura", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.Factura", "Factura")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("FK_factura_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supermercado.Shared.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("FK_producto_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Factura", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.Movimiento", "Movimiento")
                        .WithMany("Facturas")
                        .HasForeignKey("FK_movimiento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Movimiento", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.TipoDcto", "TipoDcto")
                        .WithMany()
                        .HasForeignKey("FK_codigo_tipodoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Supermercado.Shared.Entities.Consecutivo", "Consecutivo")
                        .WithMany()
                        .HasForeignKey("FK_consecutivo_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Supermercado.Shared.Entities.Tercero", "Tercero")
                        .WithMany()
                        .HasForeignKey("FK_tercero_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Supermercado.Shared.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FK_usuario_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consecutivo");

                    b.Navigation("Tercero");

                    b.Navigation("TipoDcto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Pago_Factura", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.Factura", "Factura")
                        .WithMany("PagosFactura")
                        .HasForeignKey("FK_factura_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supermercado.Shared.Entities.Metodos_Pago", "MetodoPago")
                        .WithMany("PagosFactura")
                        .HasForeignKey("FK_id_metodo_pago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Producto", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.Categoria_Producto", "Categoria")
                        .WithMany()
                        .HasForeignKey("FK_categoria_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supermercado.Shared.Entities.Tarifa_IVA", "TarifaIVA")
                        .WithMany()
                        .HasForeignKey("FK_codigo_iva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("TarifaIVA");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Tercero", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.TiposIdentificacion", "ID")
                        .WithMany()
                        .HasForeignKey("FK_codigo_ident")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ID");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Usuario", b =>
                {
                    b.HasOne("Supermercado.Shared.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("FK_rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Factura", b =>
                {
                    b.Navigation("DetallesFactura");

                    b.Navigation("PagosFactura");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Metodos_Pago", b =>
                {
                    b.Navigation("PagosFactura");
                });

            modelBuilder.Entity("Supermercado.Shared.Entities.Movimiento", b =>
                {
                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
